---
name: CI - Linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # This workflow contains a single job called "build"
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Checkout Adfinis lint-rules
      - uses: actions/checkout@v2
        with:
          repository: adfinis-sygroup/ansible-lint-rules
          path: lint-rules

      - name: ansible-lint
        uses: ansible/ansible-lint@main
        with:
          targets: icinga2_web
          args: "-R -r lint-rules"
          override-deps: |
            ansible~=2.10
            ansible-lint~=5.0
      - name: yamllint
        uses: karancode/yamllint-github-action@v2.0.0
